/**
 * Base entity interface for all FuelGuard domain entities.
 * @remarks IDs match the numeric Long values generated by the backend.
 * @author FuelGuard Platform
 */
export interface BaseEntity {
  id: number;
}
